# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(703, 813)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("padding: 0;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 650, 450))
        self.label.setStyleSheet("margin: 0;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.search_area = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_area.setGeometry(QtCore.QRect(10, 20, 461, 31))
        self.search_area.setObjectName("search_area")
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(480, 20, 93, 28))
        self.search_btn.setObjectName("search_btn")
        self.reset_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(580, 20, 93, 28))
        self.reset_btn.setObjectName("reset_btn")
        self.address_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.address_error.setGeometry(QtCore.QRect(30, 620, 641, 101))
        self.address_error.setText("")
        self.address_error.setObjectName("address_error")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map app"))
        self.search_btn.setText(_translate("MainWindow", "Искать"))
        self.reset_btn.setText(_translate("MainWindow", "Сброс"))
